//! Stress test suite entrypoint.
//!
//! Responsibilities in this file:
//! - Aggregates intentionally heavy scenarios that are excluded from default `zig build test`.
//! - Provides an opt-in root for stress/performance-oriented validation.
//! - Generated by scripts/generate_test_suites.sh; do not edit by hand.
comptime {
    _ = @import("mutations/stress_mutations_test.zig");
    _ = @import("runtime_rss_gate_test.zig");
    _ = @import("spill_phase2_gate_collector_contracts_test.zig");
    _ = @import("spill_phase2_gate_nested_hash_spill_contracts_test.zig");
    _ = @import("spill_phase2_gate_nested_selection_contracts_test.zig");
    _ = @import("spill_phase2_gate_scan_contracts_test.zig");
}
