//! Internal robustness suite entrypoint.
//!
//! Responsibilities in this file:
//! - Aggregates non-user-facing durability and maintenance tests.
//! - Keeps internal correctness coverage discoverable outside feature specs.
//! - Generated by scripts/generate_test_suites.sh; do not edit by hand.
comptime {
    _ = @import("durability/file_backend_restart_durability_test.zig");
    _ = @import("durability/index_reclaim_replay_correctness_test.zig");
    _ = @import("durability/overflow_reclaim_crash_matrix_test.zig");
    _ = @import("durability/overflow_reclaim_replay_test.zig");
    _ = @import("durability/overflow_replay_tx_markers_test.zig");
    _ = @import("integer_multi_column_matrix_test.zig");
    _ = @import("maintenance/index_reclaim_surface_test.zig");
    _ = @import("maintenance/overflow_reclaim_drain_policy_test.zig");
    _ = @import("maintenance/overflow_reclaim_surface_test.zig");
    _ = @import("maintenance/reclaim_concurrency_matrix_test.zig");
    _ = @import("maintenance/reclaim_snapshot_blocking_test.zig");
    _ = @import("query_protocol/tree_response_test.zig");
    _ = @import("runtime/planner_overflow_test.zig");
    _ = @import("server/reactor_queueing_admission_test.zig");
    _ = @import("server/reactor_queueing_max_inflight_test.zig");
    _ = @import("server/reactor_queueing_progress_test.zig");
    _ = @import("server/reactor_transaction_pinning_test.zig");
    _ = @import("server/transport_progress_test.zig");
    _ = @import("spill/nested_parent_overflow_contract_test.zig");
    _ = @import("spill/temp_spill_determinism_test.zig");
    _ = @import("spill/temp_storage_surface_test.zig");
    _ = @import("spill/variable_spill_fault_test.zig");
}
