#!/usr/bin/env sh
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$repo_root"

emit_suite() {
    suite_dir="$1"
    suite_root="$2"
    header="$3"

    tmp_file=$(mktemp)
    {
        printf '%s\n' "$header"
        echo "comptime {"
        find "$suite_dir" -type f -name '*_test.zig' | LC_ALL=C sort | while IFS= read -r path; do
            rel="${path#"$suite_dir"/}"
            base=$(basename "$rel")
            case "$base" in
                *_specs_test.zig|test_env_test.zig)
                    continue
                    ;;
            esac
            printf '    _ = @import("%s");\n' "$rel"
        done
        echo "}"
    } > "$tmp_file"

    mv "$tmp_file" "$suite_root"
}

emit_suite \
    "test/unit" \
    "test/unit/unit_specs_test.zig" \
'//! Unit lane suite entrypoint.
//!
//! Responsibilities in this file:
//! - Aggregates component-level unit tests under test/unit.
//! - Keeps unit-lane discovery independent from legacy inline src tests.
//! - Generated by scripts/generate_test_suites.sh; do not edit by hand.'

emit_suite \
    "test/features" \
    "test/features/features_specs_test.zig" \
'//! Server session-path feature test suite entrypoint.
//!
//! Responsibilities in this file:
//! - Aggregates all feature scenario modules for test discovery.
//! - Defines the canonical milestone-focused feature scope under one import root.
//! - Generated by scripts/generate_test_suites.sh; do not edit by hand.'

emit_suite \
    "test/internals" \
    "test/internals/internals_specs_test.zig" \
'//! Internal robustness suite entrypoint.
//!
//! Responsibilities in this file:
//! - Aggregates non-user-facing durability and maintenance tests.
//! - Keeps internal correctness coverage discoverable outside feature specs.
//! - Generated by scripts/generate_test_suites.sh; do not edit by hand.'

emit_suite \
    "test/stress" \
    "test/stress/stress_specs_test.zig" \
'//! Stress test suite entrypoint.
//!
//! Responsibilities in this file:
//! - Aggregates intentionally heavy scenarios that are excluded from default `zig build test`.
//! - Provides an opt-in root for stress/performance-oriented validation.
//! - Generated by scripts/generate_test_suites.sh; do not edit by hand.'

emit_suite \
    "test/sim" \
    "test/sim/sim_specs_test.zig" \
'//! Deterministic simulation test suite entrypoint.
//!
//! Responsibilities in this file:
//! - Aggregates simulation fault-matrix gate tests.
//! - Keeps deterministic replay checks isolated from feature/internals lanes.
//! - Generated by scripts/generate_test_suites.sh; do not edit by hand.'
