//! Deterministic simulation test suite entrypoint.
//!
//! Responsibilities in this file:
//! - Aggregates simulation fault-matrix gate tests.
//! - Keeps deterministic replay checks isolated from feature/internals lanes.
//! - Generated by scripts/generate_test_suites.sh; do not edit by hand.
comptime {
    _ = @import("fault_matrix_sim_test.zig");
    _ = @import("fk_fault_matrix_sim_test.zig");
    _ = @import("planner_adaptation_replay_sim_test.zig");
}
