//! Unit lane suite entrypoint.
//!
//! Responsibilities in this file:
//! - Aggregates component-level unit tests under test/unit.
//! - Keeps unit-lane discovery independent from legacy inline src tests.
//! - Generated by scripts/generate_test_suites.sh; do not edit by hand.
comptime {
    _ = @import("server/pool_test.zig");
}
